### PR TITLE
Add annotation column and joinColumn for Order model

### PR DESCRIPTION
**Pull request by sahilpatel1906**

### CODE REVIEW

**Comment by Jean-005** [comment]
Cheers Sahil!

**Review by Tommybui28 — APPROVED** [review]
Excellent fix!

**Review by Aebel-Shajan — APPROVED** [review]
Great fix g

**Review by ney601 — APPROVED** [review]
Good fix!

**Review by Jean-005 — APPROVED** [review]
Excellent work!

**Pull request merged**
