### PR TITLE
Add service and Repository RouteService

### PR DESCRIPTION
**Pull request by Tommybui28**

### CODE REVIEW

**Review by Aebel-Shajan — APPROVED** [review]
looks good Timmy!

**Review by ney601 — APPROVED** [review]
I approve

**Review by Jean-005 — APPROVED** [review]
Nicely done!

**Review by sahilpatel1906 — CHANGES_REQUESTED** [review]
You are importing driver and order repositories too.

**Review by sahilpatel1906 — APPROVED** [review]

**Pull request merged**
