### PR TITLE
Add annotations to order service.

### PR DESCRIPTION
**Pull request by Aebel-Shajan**

### CODE REVIEW

**Review by sahilpatel1906 — CHANGES_REQUESTED** [review]
You removed stuff from driver controller

**Review by Tommybui28 — APPROVED** [review]
Nice Aebel

**Review by ney601 — APPROVED** [review]
Looks good

**Review by Jean-005 — APPROVED** [review]
Awesome work!

**Review by sahilpatel1906 — APPROVED** [review]

**Pull request merged**
