### PR TITLE
Feature/route display

### PR DESCRIPTION
**Pull request by ney601**

### CODE REVIEW

**Comment by Aebel-Shajan** [comment]
We deffo gotta review this together, i made a tonne of changes oops

**Comment by Aebel-Shajan** [comment]
Since we are running late, I reccomend setting the start location and pickup locations of all drivers and orders to one location. This willl make everything alot easier. We should remove start location and pickup location properties from the backend. Then add a start location property to the route entity.

**Review by sahilpatel1906 — APPROVED** [review]
Awesome work! Love the route object!

**Review by Tommybui28 — APPROVED** [review]
Excellent work on getting our RouteDisplay working

**Review by Aebel-Shajan — APPROVED** [review]
Fixed #53. Everything looks good so far. We might need to add further logic so that the route corresponding with the current user is the one thats being displayed on the map.

**Review by Jean-005 — APPROVED** [review]
Thank you, nice work!!

**Pull request merged**
