### PR TITLE
Feature/API-requests

### PR DESCRIPTION
**Pull request by Aebel-Shajan**
Add basic requests

### CODE REVIEW

**Review by Tommybui28 — APPROVED** [review]
very good aebel

**Review by sahilpatel1906 — APPROVED** [review]
Great stuff!

**Review by Aebel-Shajan — COMMENTED** [review]
Looks good so far. We still need to post a route object to the backend

**Review by Jean-005 — COMMENTED** [review]
I'm happy with it, thanks!

**Review by ney601 — APPROVED** [review]
Thank god for the getters and setters

**Pull request merged**
